//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int AccessoryID { get; set; }
        public string AName { get; set; }
        public string APhoto { get; set; }
        public string AType { get; set; }
        public string AColor { get; set; }
        public string ASeason { get; set; }
        public string AOccasion { get; set; }
    }
}
