//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottom
    {
        public int BottomID { get; set; }
        public string BName { get; set; }
        public string BPhoto { get; set; }
        public string BType { get; set; }
        public string BColor { get; set; }
        public string BSeason { get; set; }
        public string BOccasion { get; set; }
    }
}
