//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sho
    {
        public int ShoeID { get; set; }
        public string SName { get; set; }
        public string SPhoto { get; set; }
        public string SType { get; set; }
        public string SColor { get; set; }
        public string SSeason { get; set; }
        public string SOccasion { get; set; }
    }
}
