//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Top
    {
        public int TopId { get; set; }
        public string TName { get; set; }
        public string TPhoto { get; set; }
        public string TType { get; set; }
        public string TColor { get; set; }
        public string TSeason { get; set; }
        public string TOccasion { get; set; }
    }
}
